### ISSUE TITLE
Simulator is not started

### ISSUE THREAD

**Issue by yakimant** [fastlane/scan#26]
I've got this issue:
`2015-10-30 16:56:05.815 xcodebuild[53793:347720]  iPhoneSimulator: Timed out waiting 120 seconds for simulator to boot, current state is 1.`

I've got it before tunning xcodebuild (xctool didn't have this issue).
It is solved by running the simulatore (instrument -w or ios-sim).

But maybe it can be solved inside scan?

Appreciate you work!

**Comment by xfreebird** [comment]
@yakimant mostly likely you have a slow machine. are your running on a CI box or manually from command line ?

@KrauseFx in `xctest` that was tackled by retrying the execution of tests if such a message would appear.

**Comment by yakimant** [comment]
It was on my laptop. I cant increase timeout to be sure.
But even can't see the simulator window opening.

Also - We had such case on CI with plain xcodebuild and fixed it with simulator running
We also have some projects not failing with this issue. It must be some xcodebuild error.

**Comment by xfreebird** [comment]
@yakimant have you checked the xcodebuild log ? `~/Library/Logs/scan`

**Comment by yakimant** [comment]
Hmm, it suddenly disappeared. Will play around and post here the updates.

**Comment by yakimant** [comment]
Ok, I'm getting this issue even with `-destination-timeout 500`.
From log I can't see anything suspicious.

**Comment by xfreebird** [comment]
`-destination-timeout` is for real devices, it doesn't help when using simulators

**Comment by yakimant** [comment]
Anyway, it didn't help, so I'm starting the simulator manually as before:
`Process.fork { system "xcrun instruments -t 'Blank' -l 1 -w '#{options[:device]    } (#{options[:os]})'" }`
And killing afterwards:
`killall "Simulator"`

**Comment by yakimant** [comment]
Should this be closed?
I can think of two ways of fix:
1) add scan parameter to run/stop simulator explicitly
2) add run/stop simulator actions

**Comment by alexanderjrobinson** [comment]
I am seeing the same issue. Runs fine on my local machine but not on my CI server which is a reasonably powerful Mac Mini. It works sometimes but more often than not the build fails waiting on the simulator.

In my case the simulator is launched (possibly from a previous build), so it is at least launching the simulator.

**Comment by nitinalabur** [comment]
Runs fine on my CI server, when I run it myself, but fails when jenkins on the same machine tries to run scan as part of a lane. (getting the 120 second timeout error)

**Comment by scottrhoyt** [comment]
+1. Good on local. Fails on CI running on a VM (Bitrise).

**Comment by alexanderjrobinson** [comment]
Any update or workaround for this issue?

**Comment by scottrhoyt** [comment]
My workaround is to test using xctool as opposed to scan.

**Comment by scottrhoyt** [comment]
Anyone able to verify if this is fixed in 7.2.1:

> Command line tool 'xcodebuild test' will no longer time out waiting for Simulator.app to launch

**Comment by alexanderjrobinson** [comment]
I am still seeing the same issue on the CI server after upgrading to 7.2.1.

`iPhoneSimulator: Timed out waiting 120 seconds for simulator to boot, current state is 1.`

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1943. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
