### ISSUE TITLE
Add support for output_name parameter

### ISSUE THREAD

**Issue by sguillope** [fastlane/scan#27]
It would be nice if it was possible to specify the name of the output file (similar to `gym`'s `output_name` parameter).
We are running our tests on Bamboo but the [Junit Parser plugin](https://confluence.atlassian.com/bamboo/junit-parser-289277056.html) only seems to parse files with an `.xml` extension. We currently have to manually rename the output file `report.junit` to have the `.xml` extension.

**Comment by KrauseFx** [comment]
@sguillope It's probably best to add a `mv` command after running `scan`, as even if you'd specify an output name, it might not include the extension.

**Comment by xfreebird** [comment]
@KrauseFx is there a reason why you used the `.junit` file extension ? since most the tools I know creates the JUnit report with  the `.xml` extension.

**Comment by KrauseFx** [comment]
@xfreebird I think it was default of `xcpretty`

**Comment by xfreebird** [comment]
from `xcpretty` I see that the default report name is `build/reports/junit.xml`

The file name is coming from `scan/report_collector.rb` in `generate_commands`:

``` ruby

        file_name = "report.#{type}"
        output_path = output_file_name || File.join(File.expand_path(Scan.config[:output_directory]), file_name)
```

I think it would be better to use a different name for `report.junit`, something like `junit/TEST-report.xml`. This is a wide used name format for junit tests reports.

**Comment by KrauseFx** [comment]
Sounds good to me :+1:

**Comment by Tokuriku** [comment]
Any advances made on this issue?

**Comment by jacobvanorder** [comment]
:+1:

**Comment by jeeftor** [comment]
I fully agree with this!   .xml would make things more compatible with bamboo

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1942. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
