### ISSUE TITLE
Crash on build when executing test on project with appname containing a simple quote (')

### ISSUE THREAD

**Issue by Valpertui** [fastlane/scan#47]
Issue b1453ecee8c346abeaa057febff059f0

```
[10:52:22]: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace './FidMarques.xcworkspace' -scheme 'sa-production' -destination 'platform=iOS Simulator,id=55B224A6-563F-4DB5-818A-A5948F38B356' -enableCodeCoverage YES clean build test | tee '/Users/valentin/Library/Logs/scan/Savourez l'Alsace-sa-production.log' | xcpretty
Loading...
sh: -c: line 0: unexpected EOF while looking for matching `''
sh: -c: line 1: syntax error: unexpected end of file
sh: -c: line 0: unexpected EOF while looking for matching `''
sh: -c: line 1: syntax error: unexpected end of file
[10:52:22]: Exit status: 2
[10:52:22]: Variable Dump:
[10:52:22]: {:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>"sla", :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios test"}
[10:52:22]: Error building/testing the application - see the log above
```

Bug : My app name contains a simple quote, causing the build to crash

Solution : Replace all simple quotes of the generated command by escaped double quotes in https://github.com/fastlane/scan/blob/master/lib/scan/test_command_generator.rb

**Comment by KrauseFx** [comment]
> Solution : Replace all simple quotes of the generated command by escaped double quotes in 

But then this breaks apps with `"` in the name, right? :wink:

**Comment by Valpertui** [comment]
I would think that `'` are much more common in Product Names than `"`, but you are right, the correct way to do it would be to properly escape the whole string, or to simply delete the specials characters for the generated log path :  
actual : `"\(productName)-\(schemeName).log"`  
optimal : `"\((productName + "-" + schemeName).escapedString).log"`  
I will look into doing a PR to fix it later this week but if you can fix it faster than me, don't hesitate :smile:

**Comment by KrauseFx** [comment]
Thanks @Valpertui :+1:

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1940. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
