### ISSUE TITLE
scan hangs after running tests (process doesn't exit; I'm not returned to the shell)

### ISSUE THREAD

**Issue by alex-hunsley-zonal** [fastlane/scan#49]
I'm using scan to run my iOS app tests. I'm invoking it merely as 'scan' in the root of my iOS project. It runs all the tests but then just hangs. By 'hang' I mean that control isn't returned to the shell, I have to do CTRL-C.

When I do CTRL-C I see the following text:

```

        Executed 181 tests, with 0 failures (0 unexpected) in 41.231 (45.663) seconds


^C/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.27.0/lib/fastlane_core/command_executor.rb:27:in `each': Interrupt
    from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.27.0/lib/fastlane_core/command_executor.rb:27:in `block in execute'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.27.0/lib/fastlane_core/command_executor.rb:26:in `spawn'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.27.0/lib/fastlane_core/command_executor.rb:26:in `execute'
    from /Library/Ruby/Gems/2.0.0/gems/scan-0.3.2/lib/scan/runner.rb:23:in `test_app'
    from /Library/Ruby/Gems/2.0.0/gems/scan-0.3.2/lib/scan/runner.rb:9:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/scan-0.3.2/lib/scan/manager.rb:10:in `work'
    from /Library/Ruby/Gems/2.0.0/gems/scan-0.3.2/lib/scan/commands_generator.rb:41:in `block (2 levels) in run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/scan-0.3.2/lib/scan/commands_generator.rb:60:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/scan-0.3.2/lib/scan/commands_generator.rb:14:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/scan-0.3.2/bin/scan:6:in `<top (required)>'
    from /usr/bin/scan:23:in `load'
    from /usr/bin/scan:23:in `<main>'
```

I've tried invoking scan by using fastlane and a Fastfile and the same thing happens.

**Comment by alex-hunsley-zonal** [comment]
Sorry, here's the console output in code formatting shape:

```


^C/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.27.0/lib/fastlane_core/command_executor.rb:27:in `each': Interrupt
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.27.0/lib/fastlane_core/command_executor.rb:27:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.27.0/lib/fastlane_core/command_executor.rb:26:in `spawn'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.27.0/lib/fastlane_core/command_executor.rb:26:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.3.2/lib/scan/runner.rb:23:in `test_app'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.3.2/lib/scan/runner.rb:9:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.3.2/lib/scan/manager.rb:10:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.3.2/lib/scan/commands_generator.rb:41:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.3.2/lib/scan/commands_generator.rb:60:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.3.2/lib/scan/commands_generator.rb:14:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.3.2/bin/scan:6:in `<top (required)>'
	from /usr/bin/scan:23:in `load'
	from /usr/bin/scan:23:in `<main>'
```

**Comment by PycKamil** [comment]
I have exactly same problem with scan, process just hangs
![screen shot 2015-12-16 at 17 59 59](https://cloud.githubusercontent.com/assets/1215063/11847667/dea1ed2e-a41e-11e5-88e8-8e4cc78f0d7f.png)

**Comment by rodrigo-galba** [comment]
Hi @alex-hunsley-zonal, 

I'm trying to reproduce this error, so, could you share basic info about your environment. More precisely, version info:

1 - Ruby
2 - Mac OS X
3 - iOS simulator
4 - Xcode
5 - Fastlane

In addition, could you share the relevant output when running `scan` on your machine with command of the xcode?

**Comment by kwoylie** [comment]
I had the same problem. And below are my details:
Ruby ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin15]
Mac OS 10.11.2
iOS simulator: iPhone 6s
Xcode: 7.2 (7C68)
Fastlane: 1.53.0
Scan: 0.4.1 (Same problem when I updated to 0.4.2)

|                         Summary for scan 0.4.1                         |
+-----------------------+------------------------------------------------+
| workspace             | ./guardian.xcworkspace                         |
| device                | iPhone 6s                                      |
| scheme                | guardian-qa                                    |
| clean                 | true                                           |
| code_coverage         | false                                          |
| output_directory      | ./fastlane/test_output                         |
| output_types          | html,junit                                     |
| buildlog_path         | ~/Library/Logs/scan                            |
| open_report           | false                                          |
| xcargs                | -derivedDataPath build -enableCodeCoverage YES |
| skip_slack            | false                                          |
| slack_only_on_failure | false                                          |

**Comment by gabek** [comment]
I'm running into the same thing.

**Comment by sfranusic** [comment]
I am seeing the same behavior as described above. 
1. Ruby: ruby-2.0.0-p576 (I used RVM to set it up)
2. Mac OS: 10.11.2
3. iOS Simulator: iPhone 6s
4. Xcode 7.2.1
5. fastlane_core (0.36.1) 
6. scan 0.4.2

**Comment by jinjorge** [comment]
running into the same issue. details of my setup below
1. Ruby 
2. Mac OS: 10.11.4
3. iOS Simulator: iPhone 6s
4. Xcode 7.2.1
5. Fastlane: 1.53.0
6. Scan: 0.4.2

Scan summary

```
+-----------------------+----------------------------+
|               Summary for scan 0.4.2               |
+-----------------------+----------------------------+
| workspace             | ./App.xcworkspace |
| device                | iPhone 6s                  |
| scheme                | Disneyland                 |
| clean                 | true                       |
| code_coverage         | false                      |
| output_directory      | ./test_output              |
| output_types          | html                       |
| buildlog_path         | ~/Library/Logs/scan        |
| open_report           | false                      |
| skip_slack            | false                      |
| slack_only_on_failure | false                      |
+-----------------------+----------------------------+
```

**Comment by sofacoder** [comment]
I had the same problem when my scheme is containing (activated for testing) a test target that is empty (no test classes at all). 

And by the way, the Xcode CI has the same problem as well.

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1939. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
