### ISSUE TITLE
Test marked with the `@available(iOS 9.0, *)` decorator are ran on a iOS 8 simulator

### ISSUE THREAD

**Issue by steprescott** [fastlane/scan#85]
When running `scan` specifying no device it compiles the project and then proceeds to run the test using iOS 8.4. Within the project there are tests that have the new `@available(iOS 9.0, *)` decorator because they test components that use iOS 9 APIs.

XCTest takes note of these and will only run tests that are intended for the current OS whereas Scan does not.

This results in the simulator closing the app with leaving scan hanging.

When running scan with a specified iOS 9 device all works fine.

`scan -a 'iPhone 6 (9.2)'`

New feature suggestion is that you listen to these decorators and only run them if they match the current OS that is under test.

**Comment by mpirri** [comment]
@steprescott Can you check the latest version, `scan 0.5.2` and tell us if this is still an issue? We have fixed the simulator selection logic in that version, and we are optimistic that it will resolve issues like yours. Thanks!

**Comment by mpirri** [comment]
Actually, re-reading your request, I might be off on my comment, ha.  Question: what is the deployment target set to for your test's Host Application? Our change ensures that we don't accidentally pick a simulator that doesn't match your deployment target.

Considering that `scan` is using `xcodebuild ... test` to run the tests (and thus, doing the same as what Xcode is doing), I'm somewhat surprised that scan is behaving differently than Xcode is.

**Comment by steprescott** [comment]
So my deploy target is 8.0 but there are tests that are for iOS 9 features. I will do an update of scan and see if it works at some point. Thanks

**Comment by mpirri** [comment]
Interesting.  So, I'd guess this change won't fix anything for you. I'm still somewhat surprised that `scan` is behaving differently than Xcode is. I will look into this further and see if I can understand why this might be happening.

Incidentally, are you able to reproduce the same behavior as `scan` by running `xcodebuild` from the command line?

Specifically, you can try (this example is from the `scan` GitHub front page):
`xcodebuild \`
`-workspace MyApp.xcworkspace \`
`-scheme "MyApp" \`
`-sdk iphonesimulator \`
`-destination 'platform=iOS Simulator,name=iPhone 6,OS=8.4' \`
`test`

This should do more-or-less the same as what `scan` does - let me know if this works for you. Thanks!

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1933. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
