### ISSUE TITLE
Scan hangs running test against target with missing linked files

### ISSUE THREAD

**Issue by micnguyen** [fastlane/scan#96]
Hi,

I've been using scan for a bit and it's been working great. 

I have recently added a new Target and a new test for that target (that is a duplicate of the 1st test but with the target app changed). When I do CMD+U in Xcode to run, it fails on the test because the new Target didn't have some files linked when you add a file (that checkbox that appears when adding new files to a project). That's all fine - but when I try and run a scan on the project with the missing linked files, it just stalls and doesn't error out on any compilation.

**Comment by hokster7** [comment]
Same here. I've been slowly moving my codebase to using Carthage for dependency management and often rely on errors like the following to get my tests fixed:

```
2016-02-26 02:10:59.434 xctest[66043:748130] The bundle “MyTests” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
2016-02-26 02:10:59.436 xctest[66043:748130] (dlopen_preflight(~/Library/Developer/Xcode/DerivedData/Root-hayabszkpldtmbcjgnpajteymhnb/Build/Products/Debug-iphonesimulator/MyTests.xctest/MakeEatSeeKitITests): Library not loaded: @rpath/Result.framework/Result
  Referenced from: ~/Library/Developer/Xcode/DerivedData/Root-hayabszkpldtmbcjgnpajteymhnb/Build/Products/Debug-iphonesimulator/MyTests.xctest/Frameworks/ReactiveCocoa.framework/ReactiveCocoa
  Reason: image not found)
Program ended with exit code: 82
```

**Comment by mfurtak** [comment]
Hi folks - if possible, can you please provide some more information about your setup? It would be good to know your:
- Mac OS version
- Xcode version
- fastlane version
- scan version

Also, if you can provide the full command output (until it hangs :frowning:) when running with the `--verbose` flag, that would be :100:!

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1929. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
